version: "3"

services:
  gdnsd:
    image: gdnsd
    hostname: gdnsd
    container_name: gdnsd
    restart: always
    network_mode: "bridge"
    ports:
      - "53:53"
    volumes:
      - ./conf/:/etc/gdnsd/
    build:
      context: .
      args:
        GDNS_VER: 2.3.1
